{% set name = "rawpy" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/letmaik/rawpy/archive/v{{ version }}.tar.gz
  sha256: a97feea139a42d89024c983d1321ed5c374a2bdd8cb45f73d6bea37402c08998
  patches:
    - patches/0001-Fix-include-path.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - libraw
    - numpy
    - pip
    - python
    - setuptools
  run:
    - numpy
    - python
    - scikit-image

test:
  imports:
    - rawpy
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/letmaik/rawpy
  summary: RAW image processing for Python, a wrapper for libraw
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
