{% set name = "rawpy" %}
{% set version = "0.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/letmaik/rawpy/archive/v{{ version }}.tar.gz
  sha256: 9ed0023e6d52a0160813c502f54130f78e0cc3e50ea7e43edb90fe7e10f4a747
  patches:
    - patches/0001-Fix-include-path.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - libraw
    - numpy
    - pip
    - python
    - setuptools
  run:
    - numpy
    - python
    - scikit-image

test:
  imports:
    - rawpy
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/letmaik/rawpy
  summary: RAW image processing for Python, a wrapper for libraw
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
