schema_version: 1

context:
  name: rawpy
  version: "0.27.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/letmaik/rawpy/archive/v${{ version }}.tar.gz
  sha256: b0e9af3e44a7bb2e66c6c9b4c8e397d0fa2ba307e0e8dc76d2de7ad76d84cba6
  patches:
    - patches/0001-Fix-include-path.patch

build:
  number: 0
  script:
    - if: unix
      then: bash "${RECIPE_DIR}/build.sh"
    - if: win
      then: call "%RECIPE_DIR%\\build.bat"

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - pkg-config
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - cython
        - numpy
        - pip
        - python
        - setuptools
        - wheel
  host:
    - cython
    - libraw
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - numpy
    - python
    - scikit-image

tests:
  - python:
      imports:
        - rawpy
  - script:
      - pip check
      - python run_test.py
    files:
      recipe:
        - run_test.py
    requirements:
      run:
        - pip
        - python

about:
  homepage: https://github.com/letmaik/rawpy
  repository: https://github.com/letmaik/rawpy
  summary: RAW image processing for Python, a wrapper for libraw
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
